# Generated by Django 3.0.5 on 2024-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Birthdate', models.DateTimeField(auto_now=True)),
                ('Score', models.IntegerField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
            ],
        ),
    ]
