# Generated by Django 3.2.25 on 2024-03-27 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20240324_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
